name: Update

on:
  workflow_dispatch:
  label:
    types:
      - created # for test
  schedule:
      - cron: '0 19 * * 5' # 03:00 Beijing time every day

permissions:
  contents: write
  issues: write

jobs:
  update_daily_papers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Update papers
      run: |
        python main.py

    - name: Commit and push changes
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.TOKEN }}
        push-branch: 'main'
        commit-message: '✏️ Update papers automatically.'
        force-add: 'true'
        files: README.md .github/ISSUE_TEMPLATE.md

    - name: Create an issue to notify
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          const { data: issue } = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Weekly Update Notification',
            body: 'The papers have been updated successfully.',
            labels: ['update', 'weekly']
          });
          console.log(`Created issue ${issue.number}`);